"""empty message

Revision ID: 107cd57a9f0b
Revises: cf21331eff81
Create Date: 2024-11-30 15:49:06.475132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107cd57a9f0b'
down_revision = 'cf21331eff81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
